
import utils.Validator

/**
 * When compression is needed, the program takes 3 parameters:
 *
 * Path to Input directory. This directory will contain some files and folders.
 * Path to Output directory. This is where the program should write the compressed files to.
 * Maximum compressed size per file expressed in MB.
 * When decompression is needed, the program takes 2 parameters:
 *
 * Path to Input directory. This directory contains the compressed files that were generated by the same program.
 * Path to Output directory. This is where the program should put the decompressed files & folders.
 *
 * author Bhaskar Sharma
 * */
object Driver extends App  {
      new Validator().validateArgs(args)
}

